# Generated by Django 3.0.7 on 2020-06-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgImage', models.TextField()),
                ('companyName', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('scale', models.CharField(max_length=100)),
                ('jobs', models.CharField(max_length=100)),
                ('skills', models.TextField()),
            ],
        ),
    ]
