# Generated by Django 3.0.7 on 2020-06-26 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='companies',
            table='companies',
        ),
    ]
