# Generated by Django 3.0.7 on 2020-06-27 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20200627_1023'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='skill_set',
            table='skills_set',
        ),
    ]
