# Generated by Django 3.0.7 on 2020-06-27 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200627_1041'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='skill_set',
            table='skills',
        ),
    ]
